### ISSUE TITLE
How to make network configuration hardware-agnostic?

### ISSUE THREAD

**Issue by Luke-Jaeger** [PJ-Singh-001/Cubic#222]
I have a fleet of Dell 5490's and this network configuration works:
```
 network:
    version: 2
    ethernets:
      enp0s31f6:
        dhcp4: true
```
But when I try it on other models, the computer boots up with no wired network connection because the interface has a different name, like **eno1** or whatever.

How can I generalize the user-data file so that the installer sets up wired ethernet regardless of interface name?

**OS Information:**
 - OS/Distro Name: Ubuntu
 - OS Version Ubuntu 22.04

**Cubic Information:**
 - Cubic Version: 2023.05.83
 - ISO Customizing: Ubuntu server 22.04
 - Download Link:    https://nnenix.mm.fcix.net/ubuntu-releases/22.04.2/ubuntu-22.04.2-live-server-amd64.iso
