### ISSUE TITLE
ubuntu 22.04 , autoinstall with user-data not working

### ISSUE THREAD

**Issue by changchichung** [PJ-Singh-001/Cubic#266]
**Describe the question**

I following the instruction in here , add user-data/meta-data , update grub/loopback.cfg  and then make a iso file
https://github.com/PJ-Singh-001/Cubic/issues/101#issuecomment-1336728758

but boot from the iso does not run the auto install

**What you have tried**
add user-data/meta-data in preseed folder
![](https://i.imgur.com/FyEVY0c.png)
update grub/loopback.cfg
![](https://i.imgur.com/yPfJ29z.png)

part of my user-data
```
#cloud-config
autoinstall:
  identity:
    hostname: ubuntu
    realname: Ubuntu user
    username: ubuntu
    password: "$6$1deb934eb89e6d28$Dvr8HQRlBvpX4PVSLB0tOcQqfD38L8glDWIk.tjQQNMh9OvXqhz45hPEC6yoJSMWGTvOdUX8n.f7XZ5EbtJy.1"
  # Let NetworkManager manage all devices on this system
  network:
    version: 2
    renderer: NetworkManager
  refresh-installer:
    update: no
  keyboard:
    layout: us 
    toggle: null
    variant: ''
  locale: zh_TW.UTF-8
  storage:
    grub:
      reorder_uefi: False
    layout:
      name: direct
```

**Expected behavior**

auto install from the bootable ISO

**OS Information (please complete the following information):**
 - OS/Distro Name:  ubuntu 
 - OS Version: 22.04.3

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.09.84
 - ISO Customizing: ubuntu-22.04.1-desktop-amd64.iso
 - Download Link:  https://old-releases.ubuntu.com/releases/jammy/ubuntu-22.04.1-desktop-amd64.iso
