### ISSUE TITLE
Installed packages via apt in Cubic Terminal don't exist in the final ISO

### ISSUE THREAD

**Issue by misiek303** [PJ-Singh-001/Cubic#295]
**Describe the bug**
Additional packages installed in the Cubic terminal are not in the final ISO. 

**To Reproduce**

1. Download the ubuntu-22.04.4-live-server-amd64.iso
2. Run Cubic
3. run: apt install mate-desktop-environment
4. Goto Pressed Tab
5.  add user-data with below content

```
#cloud-config
autoinstall:
  version: 1
  # Update the installer?
  refresh-installer:
  update: no
  # interactive-sections:
  # - storage
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:
    hostname: ubuntu-server
    password: "$6$mCIda/uYttHgKzCk$fyfyXlBL4efcjO"
    username: ubuntu
    
  ssh:
    install-server: true
    allow-pw: yes
```
6. Goto boot and modify grub.cfg

```
set timeout=30

loadfont unicode

set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

menuentry "Install Custom Server (Automated)" {
  set gfxpayload=keep
  linux     /casper/vmlinuz boot=casper autoinstall "ds=nocloud;s=/cdrom/preseed/" ---
  initrd    /casper/initrd.gz
}

grub_platform
```

7. Generate and install ISO

Package mate-desktop-environment should be installed.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu Server
 - OS Version: 22-04.4-live-server-amd64

**Cubic Information (please complete the following information):**
 - Cubic Version: 1.26.0
 - ISO Customizing: ubuntu-22.04.4-live-server-amd64.iso
