### ISSUE TITLE
all attempts to copy files fails

### ISSUE THREAD

**Issue by misiek303** [PJ-Singh-001/Cubic#296]
What is the best way to copy the files? 
I don't want to add here all my attempts but I tried late-commands with and without **curtin in-target --target=/target**. I tried '**runcmd**' as well. Below is my last attempt

```
  late-commands:
    - curtin in-target --target=/target -- dpkg-reconfigure lightdm
    - curtin in-target --target=/target -- sudo mkdir -p /home/ubuntu/Desktop
    - curtin in-target --target=/target -- sudo chown -R ubuntu:ubuntu /home/ubuntu/Desktop
    - curtin in-target --target=/target -- sudo mv /home/software.AppImage /home/ubuntu/Desktop/.
  ```

```
  runcmd:
    - [ systemctl, enable, "grafana-server" ]
    #- [ mv, "/home/software.AppImage","/home/ubuntu/Desktop/."]
    #- [ bash, "/home/install-node-red.sh"] 

```

I have my software.AppImage in the /home uploaded from the Cubic Terminal. I can confirm the files are there when I install and boot the ISO. But I want to copy them into the Desktop folder for the user created in pressed/user-data

```
#cloud-config
autoinstall:
  version: 1
  # Update the installer?
  refresh-installer:
  update: no
  # interactive-sections:
  # - storage
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:
    hostname: my-server
    password: "$6$mCIda/uYttHgKzCk$fyfL3awIlVn0ROrUgO9ak51l/sHYOwhE/ke8/"
    username: ubuntu
```

The last attempt failed on "sudo chown -R ubuntu:ubuntu /home/ubuntu/Desktop"

<img width="668" alt="Screenshot 2024-03-09 at 5 41 55 PM" src="https://github.com/PJ-Singh-001/Cubic/assets/371344/815f9a1f-f07e-439b-9d97-e72705a1f0b3">

**It also fails on the "move" command as well.** I am not sure what the problem is. There is no error message telling me what the issue is.

I would like to eventually copy them from **preseed/files/** but I have not tried this yet. If you can point me in the right direction of what is the best way to copy the files to the user environment, that would be great.

Thanks
