### ISSUE TITLE
Unable to install customized ISO in QEMU Emulator.

### ISSUE THREAD

**Issue by axi92** [PJ-Singh-001/Cubic#373]
**Describe the bug**

Auto install is not working because apparently ubuntu does not find the disc that QEMU is providing with Cubic.

**To Reproduce**

Ubuntu 24.04 iso
With this user-data
Some additional file changes:
- custom-disk/boot/grub/grub.cfg add
```
menuentry "Ubuntu autoinstall test" {
 set gfxpayload=keep
 linux /casper/vmlinuz "ds=nocloud;s=/cdrom/nocloud/" debug autoinstall ---
 initrd /casper/initrd.gz
}
```
- custom-disk/nocloud/meta-data empty
- custom-root/usr/local/share/ca-certificates/root.crt
- custom-root/etc/sudoers.d/admin
- custom-root/etc/ssh/ssh_config.d/custom.conf

```yaml
#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: yes
  locale: en_US.UTF-8
  timezone: "Europe/Vienna"
  updates: all
  shutdown: poweroff
  keyboard:
    layout: us
  identity:
     hostname: generic
     username: admin
     password: $6$osOGMhW29K1VXSD.$b/93PnDVyfXTeTWGQyngZ0NW0a/N5pfQMY5jsBFsTiTodvqEdfgxHLB/Iaz0ziJzEXnKOcVlZpOyKZIjXQfZR.
  user-data:
    disable_root: false
  ssh:
     install-server: yes
     allow-pw: yes
  packages:
    - curl
    - git
    - gpg
  error-commands:
    - tar -czf /installer-logs.tar.gz /var/log/installer/
    - journalctl -b > /installer-journal.log
```

**Expected behavior**

To install ubuntu as described.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 24.04

**Cubic Information (please complete the following information):**
 - Cubic Version: 2024.09.89
 - ISO Customizing: ubuntu-24.04.1-live-server-amd64.iso
 - Download Link: https://releases.ubuntu.com/24.04.1/ubuntu-24.04.1-live-server-amd64.iso

**Cubic Log:**

 Cut and paste the log after running `cubic --verbose` from the command line

**Screenshots**

![Image](https://github.com/user-attachments/assets/af26fcc1-bd9a-4e4e-9f2f-64ce401fe8d5)

I tried the storage part interactive but got this error:
``` 
  interactive-sections:
    - storage
```

![Image](https://github.com/user-attachments/assets/012fa44d-4aa6-43a3-9a7a-6f21c1250d22)

Then I opened the shell with `df -h`

![Image](https://github.com/user-attachments/assets/3a115540-e2dd-47ae-aa96-2103fa22c22b)
What should be the file system for the installation?

**Comment by Slothinger** [comment]
cant get the autoinstall to work with 24.04, even the simplest configs fail to autoinstall.
Is it possible that something is broken currently?

**Comment by slamanna212** [comment]
Also experience this behavior with Ubuntu 22

```
autoinstall:
  storage:
    layout:
      name: direct
```
