### ISSUE TITLE
Subiquity fails to start with "Something went wrong" error in Ubuntu 24.04.2 Desktop.

### ISSUE THREAD

**Issue by shonubot** [PJ-Singh-001/Cubic#394]
**Describe the bug**

Ubiquity fails to launch with a "Something went wrong" error in Ubuntu 24.04.2 Desktop.

**To Reproduce**
Run any package modification command ie. `apt update` and `apt upgrade` in the chroot.

**OS Information (please complete the following information):**
 - Ubuntu
 - Ubuntu 24.04.2 LTS

**Cubic Information **
 - Cubic Version: 2024.09.89
 - ISO Customizing: ubuntu-24.0.4.2-desktop-amd64.iso
 - Download Link: https://ubuntu.com/download/desktop/thank-you?version=24.04.2&architecture=amd64&lts=true

**Screenshots**

![Image](https://github.com/user-attachments/assets/f9fb7fd0-65ce-423a-858b-2d08621e148a)

**Comment by PJ-Singh-001** [comment]
The changes you made are very straightforward.

I'll see if I can look into this.

**Comment by joez** [comment]
I have the same issue without any customization based on Ubuntu 24.04 desktop and Ubuntu 25.04 desktop

BTW. There is another issue on Ubuntu 25.04 desktop:

Error "Unable to update the installer sources" while generating the customized disk image

I can fix this issue to apply changes on `/usr/share/cubic/cubic/pages/generate_page.py`

```python
# change the impelmentation of def _update_installer_sources_yaml function

    sources = yaml_list['sources'] if 'sources' in yaml_list else yaml_list
    for source in sources:
        if source['path'] == path:
            source['default'] = True
            source['description'] = {'en': model.custom.iso_release_name}
            source['locale_support'] = 'none'  # 'locale-only'
            source['name'] = {'en': model.custom.iso_volume_id}
            source['size'] = model.file_system_size

    return yaml_list
```

Now the ISO can be generated successfully, and it can boot up successfully.
But failed to install the OS, the installer crashes, same as @shonubot

**Comment by PJ-Singh-001** [comment]
> I have the same issue without any customization based on Ubuntu 24.04 desktop and Ubuntu 25.04 desktop
> 
> BTW. There is another issue on Ubuntu 25.04 desktop:
> 
> Error "Unable to update the installer sources" while generating the customized disk image
> 
> I can fix this issue to apply changes on `/usr/share/cubic/cubic/pages/generate_page.py`
> 
> # change the impelmentation of def _update_installer_sources_yaml function
> 
>     sources = yaml_list['sources'] if 'sources' in yaml_list else yaml_list
>     for source in sources:
>         if source['path'] == path:
>             source['default'] = True
>             source['description'] = {'en': model.custom.iso_release_name}
>             source['locale_support'] = 'none'  # 'locale-only'
>             source['name'] = {'en': model.custom.iso_volume_id}
>             source['size'] = model.file_system_size
> 
>     return yaml_list
> 
> Now the ISO can be generated successfully, and it can boot up successfully. But failed to install the OS, the installer crashes, same as [@shonubot](https://githCubic ub.com/shonubot)

@joez,

This is the right general approach. Your comment was from yesterday, but this issue was corrected in Cubic version 2025.06.90 released on June 3rd. Therefore, the fix above should no longer be necessary. Please test the latest version of Cubic (2025.06.92) and let me know if the issue is still present?

**Comment by PJ-Singh-001** [comment]
@shonubot,

I tested customizing Ubuntu 24.04.2 (`ubuntu-24.04.2-desktop-amd64.iso`) using Cubic version 2025.06.92, and I was able to successfully customize the ISO and install it.

The simple changes you made above should not have caused the issues you had experienced, so I tested by installing a single package:

    apt install tree

Once it was generated, I installed the resulting ISO in VirtualBox. The installation took a very long time, but I was able to confirm the installer's progress by opening the "Logs" application and refreshing the "All" section, which does a good job of showing what the installer is actually doing.

(As a side note, remember, you can not remove `snapd` because it is required by the installer).

Please retry your customizations using Cubic version 2025.06.92, and let me know if it works.

    sudo apt-add-repository universe
    sudo apt-add-repository ppa:cubic-wizard/release
    sudo apt update
    sudo apt install --no-install-recommends cubic

**Comment by shonubot** [comment]
I updated and installed Cubic version 2025.06.92 and generated a new .iso but when booting from it, I still experience the issue. I tried only running one command in the cubic chroot in a new project: `apt install neofetch` even then I got the same error, but when I make no changes it seems to work fine.
<br>
![Image](https://github.com/user-attachments/assets/6b2323d8-95d2-44a5-9888-b0b9ec05061e)

**Comment by PJ-Singh-001** [comment]
I'll try customizing `ubuntu-24.0.4.2-desktop-amd64.iso` and install `neofetch`.

Did you create a USB, or you tested in Virtual Box?

**Comment by shonubot** [comment]
I tested it in VMware Workstation Pro 17

**Comment by PJ-Singh-001** [comment]
Did you have network connectivity in your virtual machine?
During installation, did you opt to update the installer or install drivers?

**Comment by shonubot** [comment]
I had network connectivity but I never updated the installer or drivers

**Comment by PJ-Singh-001** [comment]
I am running Cubic 2025.06.92 in Ubuntu 24.04.2 LTS.

The only change I made was `apt install neofetch`.

During this test, I had disabled network connectivity in my VM.
But during the previous test, I had network connectivity turned on (although I declined to install any updates or drivers).

I do not get an `autoinstall` error, or the "We're sorry" error window. (As a side note, I always get the "We're sorry" window whenever I try to install a completely original, unchanged Ubuntu **25**.04 ISO on my physical computer).

Are you sure you are getting an error? The install takes a VERY long time, and it seems like it has stalled.
During installation, open the Logs app. Click on "All". To refresh it, click on "Important" and then click on "All" again. You will see a better representation of what the installer is doing, compared to the command-line output in the installer itself.

![Image](https://github.com/user-attachments/assets/d14d8ae2-d59a-4c53-a798-d3738f7232f0)

![Image](https://github.com/user-attachments/assets/c2af0087-a273-46c7-9f9a-7e3366450518)

![Image](https://github.com/user-attachments/assets/f5e3bfe8-6850-4b7e-bdf8-8903e033e83d)

![Image](https://github.com/user-attachments/assets/3093a510-cedc-490f-9e3b-1be1e7ba4548)

![Image](https://github.com/user-attachments/assets/8ec39b20-e86e-49dd-8994-dfccba976d94)

Click <kbd>Skip</kbd>...
![Image](https://github.com/user-attachments/assets/1e172d85-945b-4f0c-b705-024e66349ddf)

![Image](https://github.com/user-attachments/assets/6b7a3331-1509-4726-8f13-b7208e433272)

![Image](https://github.com/user-attachments/assets/9dd265c3-a0ee-4e1c-8e98-9387a6bc260f)

![Image](https://github.com/user-attachments/assets/9fbe7f35-9792-4c11-b0d5-de4c482055be)

![Image](https://github.com/user-attachments/assets/e9ad2984-4459-424d-8d71-20d2136efbd2)

![Image](https://github.com/user-attachments/assets/d23fa95c-854d-4354-a91d-2f04969709d6)

![Image](https://github.com/user-attachments/assets/72968877-04ce-4c5b-9b08-daa9d57f72c3)

![Image](https://github.com/user-attachments/assets/2c135b0f-a8fe-4178-b831-f69b3f20a91d)

**Comment by shonubot** [comment]
The installation does not begin as the error shows up before the Choose Your Language screen. I checked the logs app as you said and it seems that Subiquity is trying to use a auto install and cloud config which does not exist in these lines:
`subiquity/Late/apply_autoinstall_config`
`subiquity/load_cloud_config/extract_autoinstall`

![Image](https://github.com/user-attachments/assets/71aa3d50-06a3-4582-ad85-fbde77f76810)

![Image](https://github.com/user-attachments/assets/7c84c108-30b4-4d98-8ecd-161befa53077)

**Comment by PJ-Singh-001** [comment]
Paste the contents of...

(1)

    <your Cubic project directory>/custom-disk/casper/install-sources.yaml

(2)

    <your Cubic project directory>/custom-disk/casper/install-sources.yaml.original

(3)

    <your Cubic project directory>/custom-disk/boot/grub/grub.cfg

If you don't have your original Cubic project, you can use File Roller (Archive Manager) to open the generated ISO, and access these files (1 and 3 only) from your customized `*.iso` file.

**Comment by PJ-Singh-001** [comment]
One more question: After you installed Cubic 2025.06.92, did you create a brand new empty project, or did you use your existing Cubic project that you had created using an older version of Cubic?

**Comment by shonubot** [comment]
I only have 1 and 3 as I don't have the original Cubic project:

(1)
```
 - default: true
  description:
    en: ''
  id: ubuntu-desktop-minimal
  locale_support: none
  name:
    en: Better Ubuntu  24
  path: minimal.squashfs
  size: 10436231168
  type: fsimage-layered
  variant: desktop
```
(2)
```
set timeout=30

loadfont unicode

set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

menuentry "Try or Install Ubuntu" {
	set gfxpayload=keep
	linux	/casper/vmlinuz  --- quiet splash
	initrd	/casper/initrd.gz
}
menuentry "Ubuntu (safe graphics)" {
	set gfxpayload=keep
	linux	/casper/vmlinuz nomodeset  --- quiet splash
	initrd	/casper/initrd.gz
}
grub_platform
if [ "$grub_platform" = "efi" ]; then
menuentry 'Boot from next volume' {
	exit 1
}
menuentry 'UEFI Firmware Settings' {
	fwsetup
}
else
menuentry 'Test memory' {
	linux16 /boot/memtest86+x64.bin
}
fi
```

**Comment by shonubot** [comment]
I created a new cubic project

**Comment by PJ-Singh-001** [comment]
(1)
Was the space preceding `- default: true` in your `install-sources.yaml` file a cut-and-paste error, or is there  actually a space there?

(2)
I noticed the Release section (populated on the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page)) is empty.

---

I wonder if one or both of these are causing the issue? Please double check number 1, and for number 2, try adding text in the Release text field on the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page).

Your `install-sources.yaml` file is on the right, and mine is on the left...

![Image](https://github.com/user-attachments/assets/567f54df-adb1-4cbe-be25-0251326ff487)

**Comment by shonubot** [comment]
(1) Sorry, It was a copy and paste error, there is no space preceding `-default: true`

(2) I already tried adding text to the release section it did not make a difference

**Comment by PJ-Singh-001** [comment]
OK.

If you try to install using the original unmodified `ubuntu-24.04.2-desktop-amd64.iso` file in VMware, the installer launches without issue?

**Comment by shonubot** [comment]
Yes, it loads properly without any issues and installs

**Comment by shonubot** [comment]
I tried customizing other versions of Ubuntu, and they seem to work fine. I will use another version of Ubuntu until the issue is resolved

**Comment by PJ-Singh-001** [comment]
@shonubot,

I can't recreate this, so I can't debug, so I can't fix this.
I'll keep looking at this, and hopefully someone else can share their experience with this same issue and provide further insight.

**Comment by shonubot** [comment]
Ok, Thanks

**Comment by zerocoolroot** [comment]
@PJ-Singh-001  

Hi,

Firstly, I apologize for my bad English. I'm from Brazil.

I have exactly the same error as @shonubot .

I only updated the ISO with the **apt update** and **apt upgrade** commands, without adding or removing programs.

I tested it on VMWare Workstation and VirtualBox, both in their latest version. I also tested it on a physical machine.
For both scenarios I tested it with and without a network connection.

Cubic also in its latest version.

![Image](https://github.com/user-attachments/assets/2852d65b-9d0d-4e6a-b6f7-aefc06322fab)

![Image](https://github.com/user-attachments/assets/d125ee00-654e-43cf-84ac-6e1a457bcc49)

![Image](https://github.com/user-attachments/assets/aad9eb7e-b483-403e-9e4a-b1d827c55a1d)

I used versions **24.04.0**, **24.04.1** and **24.04.2**, from the links below:
https://old-releases.ubuntu.com/releases/24.04/ubuntu-24.04-desktop-amd64.iso
https://old-releases.ubuntu.com/releases/24.04/ubuntu-24.04.1-desktop-amd64.iso
https://releases.ubuntu.com/24.04/ubuntu-24.04.2-desktop-amd64.iso

My Projects are below:
https://www.mediafire.com/file/50grncttb496vt1/ubuntu-24.04.0-2025.06.26-desktop-amd64.iso/file
https://www.mediafire.com/file/1nydu9pdjnnatur/ubuntu-24.04.1-2025.06.27-desktop-amd64.iso/file
https://www.mediafire.com/file/58cyeuv5wwhiwnc/ubuntu-24.04.2-2025.06.27-desktop-amd64.iso/file

File below install-sources.yaml Ubuntu 24.04.0 - Cubic
```
- default: true
  description:
    en: Custom Noble Numbat
  id: ubuntu-desktop-minimal
  locale_support: none
  name:
    en: Ubuntu 24.04.0 LTS
  path: minimal.squashfs
  size: 8579457024
  type: fsimage-layered
  variant: deskto
```

File below install-sources.yaml Ubuntu 24.04.0 - Original

```
- default: true
  description:
    en: A minimal but usable Ubuntu Desktop.
  id: ubuntu-desktop-minimal
  locale_support: langpack
  name:
    en: Ubuntu Desktop (minimized)
  path: minimal.squashfs
  preinstalled_langs:
  - de
  - en
  - es
  - fr
  - it
  - pt
  - ru
  - zh
  - ''
  size: 4101541888
  type: fsimage-layered
  variant: desktop
  variations:
    minimal:
      path: minimal.squashfs
      size: 4474552320
    minimal-enhanced-secureboot:
      path: minimal.enhanced-secureboot.squashfs
      size: 4474552320
      snapd_system_label: enhanced-secureboot-desktop
- default: false
  description:
    en: A full featured Ubuntu Desktop.
  id: ubuntu-desktop
  locale_support: langpack
  name:
    en: Ubuntu Desktop
  path: minimal.standard.squashfs
  preinstalled_langs:
  - de
  - en
  - es
  - fr
  - it
  - pt
  - ru
  - zh
  - ''
  size: 5660524544
  type: fsimage-layered
  variant: desktop
  variations:
    enhanced-secureboot:
      path: minimal.standard.enhanced-secureboot.squashfs
      size: 5856174080
      snapd_system_label: enhanced-secureboot-desktop
    standard:
      path: minimal.standard.squashfs
      size: 5856174080
```

File below install-sources.yaml Ubuntu 24.04.1 - Cubic
```
- default: true
  description:
    en: Noble Numbat
  id: ubuntu-desktop-minimal
  locale_support: none
  name:
    en: Ubuntu 24.04.1 2025.06.27 LTS
  path: minimal.squashfs
  size: 8931934208
  type: fsimage-layered
  variant: desktop
```

File below install-sources.yaml Ubuntu 24.04.1 - Original

```
- default: true
  description:
    en: A minimal but usable Ubuntu Desktop.
  id: ubuntu-desktop-minimal
  locale_support: langpack
  name:
    en: Ubuntu Desktop (minimized)
  path: minimal.squashfs
  preinstalled_langs:
  - de
  - en
  - es
  - fr
  - it
  - pt
  - ru
  - zh
  - ''
  size: 4121833472
  type: fsimage-layered
  variant: desktop
  variations:
    minimal:
      path: minimal.squashfs
      size: 4494692352
    minimal-enhanced-secureboot:
      path: minimal.enhanced-secureboot.squashfs
      size: 4494692352
      snapd_system_label: enhanced-secureboot-desktop
- default: false
  description:
    en: A full featured Ubuntu Desktop.
  id: ubuntu-desktop
  locale_support: langpack
  name:
    en: Ubuntu Desktop
  path: minimal.standard.squashfs
  preinstalled_langs:
  - de
  - en
  - es
  - fr
  - it
  - pt
  - ru
  - zh
  - ''
  size: 5702422528
  type: fsimage-layered
  variant: desktop
  variations:
    enhanced-secureboot:
      path: minimal.standard.enhanced-secureboot.squashfs
      size: 5884710912
      snapd_system_label: enhanced-secureboot-desktop
    standard:
      path: minimal.standard.squashfs
      size: 5884710912
```

File below install-sources.yaml Ubuntu 24.04.2 - Cubic
```
- default: true
  description:
    en: Noble Numbat
  id: ubuntu-desktop-minimal
  locale_support: none
  name:
    en: Ubuntu 24.04.2 2025.06.27 LTS
  path: minimal.squashfs
  size: 9115074560
  type: fsimage-layered
  variant: desktop
```

File below install-sources.yaml Ubuntu 24.04.2 - Original

```
- default: true
  description:
    en: A minimal but usable Ubuntu Desktop.
  id: ubuntu-desktop-minimal
  locale_support: langpack
  name:
    en: Ubuntu Desktop (minimized)
  path: minimal.squashfs
  preinstalled_langs:
  - de
  - en
  - es
  - fr
  - it
  - pt
  - ru
  - zh
  - ''
  size: 4193628160
  type: fsimage-layered
  variant: desktop
  variations:
    minimal:
      path: minimal.squashfs
      size: 4573061120
    minimal-enhanced-secureboot:
      path: minimal.enhanced-secureboot.squashfs
      size: 4573061120
      snapd_system_label: enhanced-secureboot-desktop
- default: false
  description:
    en: A full featured Ubuntu Desktop.
  id: ubuntu-desktop
  locale_support: langpack
  name:
    en: Ubuntu Desktop
  path: minimal.standard.squashfs
  preinstalled_langs:
  - de
  - en
  - es
  - fr
  - it
  - pt
  - ru
  - zh
  - ''
  size: 5859082240
  type: fsimage-layered
  variant: desktop
  variations:
    enhanced-secureboot:
      path: minimal.standard.enhanced-secureboot.squashfs
      size: 5982388224
      snapd_system_label: enhanced-secureboot-desktop
    standard:
      path: minimal.standard.squashfs
      size: 5982388224
```

File below grub.cfg Ubuntu 24.04.0, 24.04.1 and 24.04.2 - Cubic

```
set timeout=30

loadfont unicode

set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

menuentry "Try or Install Ubuntu" {
	set gfxpayload=keep
	linux	/casper/vmlinuz  --- quiet splash
	initrd	/casper/initrd.gz
}
menuentry "Ubuntu (safe graphics)" {
	set gfxpayload=keep
	linux	/casper/vmlinuz nomodeset  --- quiet splash
	initrd	/casper/initrd.gz
}
grub_platform
if [ "$grub_platform" = "efi" ]; then
menuentry 'Boot from next volume' {
	exit 1
}
menuentry 'UEFI Firmware Settings' {
	fwsetup
}
else
menuentry 'Test memory' {
	linux16 /boot/memtest86+x64.bin
}
fi
```
